namespace OpenNova.Mission
{
    public enum ActionType
    {
        Null = 0,
        RedirectGroupTo = 1,
        KillGroup = 2,
        ChangeGroupAI = 3,
        VaporizeGroup = 4,
        MisvarChange = 5,
        OutputText = 6,
        PlayWavList = 7,
        BlueWin = 8,
        RedWin = 9,
        GreenWin = 10,
        GroupVelocity = 11,
        AreaAiRed = 12,
        AreaAiBlue = 13,
        SubGoalWon = 14,
        SubGoalLost = 15,
        ChangeGTeamAction = 16,
        ChangeGroupAction = 17,
        GroupTeleportAction = 18,
        RedirectSingleTo = 19,
        KillSingle = 20,
        ChangeSingleAI = 21,
        VaporizeSingle = 22,
        SingleVelocity = 23,
        ChangeSteamAction = 24,
        SingleChangeGroup = 25,
        SingleTeleportAction = 26,
        ParticleEffectAction = 27,
        GroupOpenDoorAction = 30,
        GroupCloseDoorAction = 31,
        GroupResetHasVisited = 32,
        SingleResetHasVisited = 33,
        ResetEvent = 34,
        ShowWinSubgoal = 35,
        ShowLoseSubgoal = 36,
        AttachToEmplaced = 37,
        SetLightState = 38,
        Teammates = 39,
        ShowWaypoints = 40,
        ExecuteWac = 41,
        SsnTargetSsnPri = 42,
        SsnTargetSsnExc = 43,
        SsnTargetGroupPri = 44,
        SsnTargetGroupExc = 45,
        GroupTargetSsnPri = 46,
        GroupTargetSsnExc = 47,
        GroupTargetGroupPri = 48,
        GroupTargetGroupExc = 49
    }
}
